### PR TITLE
Added french translations

### PR DESCRIPTION
**Pull request by NathanBnm**

### CODE REVIEW

**Comment by Timecraft** [comment]
I sincerely apologize that this merge will not help much, as Notifier will unlikely be updated further. I thank you extremely for your pull request, and hope that you will continue contributing to Open Source.

**Comment by NathanBnm** [comment]
Oh well, but why? This is only translations 😊

**Comment by Timecraft** [comment]
See https://github.com/Timecraft/notifier/issues/35

**Comment by Timecraft** [comment]
See Issue # 35. Do not want to provide a direct link

**Comment by NathanBnm** [comment]
I understand the point, sorry there's nothing I can really do for that, I haven't enough skills into this :smile:

**Pull request merged**
